# Generated by Django 5.2 on 2025-04-19 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='caregory',
            new_name='category',
        ),
    ]
